tradutor = {
    "livro": "book",
    "caneta": "pen",
    "caderno": "notebook",
    "mesa": "table",
    "cadeira": "chair",
    "lápis": "pencil",
    "borracha": "eraser",
    "mochila": "backpack",
    "computador": "computer",
    "telefone": "phone",
    "relógio": "watch",
    "chave": "key",
    "janela": "window",
    "porta": "door",
    "paredes": "walls",
    "teto": "ceiling",
    "chão": "floor",
    "escada": "stairs",
    "corredor": "hallway",
    "sala": "living room",
    "quarto": "bedroom",
    "banheiro": "bathroom",
    "cozinha": "kitchen",
    "jardim": "garden",
    "garagem": "garage",
    "sótão": "attic",
    "porão": "basement",
    "varanda": "balcony",
    "pátio": "patio",
    "terraço": "terrace",
    "sótão": "loft",
    "cave": "cellar",
    "sala de estar": "living room",
    "sala de jantar": "dining room",
    "pudim": "pudding",
    "bolo": "cake",
    "torta": "pie",
    "sorvete": "ice cream",
    "biscoito": "cookie",
    "doce": "candy",
    "chocolate": "chocolate",   
    "gelatina": "gelatin",
    "merengue": "meringue",
    "pavê": "trifle",
    "tapioca": "tapioca",
    "quindim": "quindim",
    "canjica": "canjica",
    "curau": "curau",
    "pavê": "pavê",
    "tapioca": "tapioca",
    "quindim": "quindim",
    "canjica": "canjica",
    "curau": "curau",
    "carro": "car",
    "moto": "motorcycle",
    "bicicleta": "bicycle",
    "ônibus": "bus",
    "trem": "train",
    "avião": "airplane",
    "navio": "ship",
    "bicicleta": "bicycle",
    "moto": "motorcycle",
    "carro": "car",
    "caminhão": "truck",
    "van": "van",
    "caminhonete": "pickup truck",
    "perua": "station wagon",
    "micro-ônibus": "minibus",
    "ciclomotor": "moped",
    "patinete": "scooter",
    "skate": "skateboard",
    "patins": "rollerblades",
    "caminhada": "walking",
    "corrida": "running",
    "natação": "swimming",
    "ciclismo": "cycling",
    "escalada": "rock climbing",
    "patinação": "ice skating",
    "surf": "surfing",
    "esqui": "skiing",
    "ginástica": "gymnastics",
    "yoga": "yoga",
    "meditação": "meditation",
    "pilates": "pilates",
    "dança": "dance",
    "musculação": "weightlifting",
    "aeróbica": "aerobics",
    "crossfit": "crossfit",
    "boxe": "boxing",
    "karatê": "karate",
    "judo": "judo",
    "taekwondo": "taekwondo",
    "capoeira": "capoeira",
    "muay thai": "muay thai",
    "kickboxing": "kickboxing",
    "boxe tailandês": "thai boxing",
    "jiu-jitsu": "jiu-jitsu",
    "taiji": "tai chi",
    "kendo": "kendo",
    "aikido": "aikido",
    "capoeira": "capoeira",
    "krav maga": "krav maga",
    "hardware": "hardware",
    "software": "software",
    "firmware": "firmware",
    "periféricos": "peripherals",
    "rede": "network",
    "servidor": "server",
    "cliente": "client",
    "roteador": "router",
    "switch": "switch",
    "firewall": "firewall",
    "modem": "modem",
    "ponto de acesso": "access point",
    "cabo": "cable",
    "conector": "connector",
    "adaptador": "adapter",
    "hub": "hub",
    "repetidor": "repeater",
    "bridge": "bridge",
    "gateway": "gateway",
    "load balancer": "load balancer",
    "proxy": "proxy",
    "vpn": "vpn",
    "firewall": "firewall",
    "servidor": "server",
    "cliente": "client",
    "roteador": "router",
    "switch": "switch",
    "modulo": "module",
    "placa-mãe": "motherboard", 
    "processador": "processor",
    "memória": "memory",
    "armazenamento": "storage",
    "disco rígido": "hard drive",
    "unidade de estado sólido": "solid state drive",
    "cartão de memória": "memory card",
    "pendrive": "flash drive",
    "nuvem": "cloud",
    "backup": "backup",
    "recuperação de dados": "data recovery",
    "armazenamento em nuvem": "cloud storage",
    "sincronização": "synchronization",
    "criptografia": "encryption",
    "compressão": "compression",
    "desduplicação": "deduplication",
    "monitoramento": "monitoring",
    "auditoria": "auditing",
    "relatório": "reporting",
    "alerta": "alerting",
    "notificação": "notification",
    "painel": "dashboard",
    "métricas": "metrics",
    "logs": "logs",
    "análise": "analysis",
    "visualização": "visualization",
    "extração": "extraction",
    "transformação": "transformation",
    "carga": "loading",
    "integração": "integration",
    "API": "API",
    "endpoint": "endpoint",
    "requisição": "request",
    "resposta": "response",
    "autenticação": "authentication",
    "autorização": "authorization",
    "token": "token",
    "casa": "house",
    "apartamento": "apartment",
    "quarto": "bedroom",
    "cozinha": "kitchen",           
    "banheiro": "bathroom",
    "garagem": "garage",
    "jardim": "garden",
    "varanda": "balcony",
    "escritório": "office",
    "lavanderia": "laundry",
    "dispensa": "pantry",
    "corredor": "hallway",
    "entrada": "entryway",
    "sótão": "attic",
    "porão": "basement",
    "pátio": "patio",
    "cobertura": "penthouse",
    "estacionamento": "parking lot",
    "quintal": "backyard",  
    "sacada": "balcony",
    "terraço": "terrace",
    "hall": "hall",
    "salão de festas": "party room",
    "espaço gourmet": "gourmet space",
    "home office": "home office",
    "sala de jogos": "game room",
    "cinema em casa": "home theater",
    "adega": "wine cellar",
    "empresa": "company",   
    "funcionário": "employee",
    "departamento": "department",
    "projeto": "project",
    "reunião": "meeting",
    "prazo": "deadline",
    "tarefa": "task",
    "responsável": "responsible",
    "status": "status",
    "prioridade": "priority",
    "comentário": "comment",
    "anexo": "attachment",
    "colaborador": "collaborator",
    "documento": "document",
    "revisão": "review",
    "aprovação": "approval",
    "feedback": "feedback",
    "recurso": "resource",
    "implementação": "implementation",
    "documentação": "documentation",
    "manutenção": "maintenance"
}


def traduzir():
    limpar_tela()
    palavra = input("Digite a palavra em português: ")
    if palavra in tradutor:
        print(f"A tradução de '{palavra}' é '{tradutor[palavra]}'.")
    else:
        print(f"Desculpe, a palavra '{palavra}' não está no dicionário de tradução.")


def main():
    while True:
        traduzir()
        input("Pressione Enter para continuar...")
        limpar_tela()

def limpar_tela():
    import os
    os.system('cls' if os.name == 'nt' else 'clear')

def menu():
    while True:
        print("1 - Traduzir palavra")
        print("2 - Sair")
        escolha = input("Escolha uma opção: ")
        if escolha == '1':
            limpar_tela()
            main()
        elif escolha == '2':
            break
        else:
            print("Opção inválida. Tente novamente.")

if __name__ == "__main__":
    menu()
    limpar_tela()
